added user to delete themselves from sso
CECS-491A/core pull request #105
Opened 2019-04-10 19:46 UTC by alfredovargasjr

# Description

SSO Functionality - Delete user from SSO and all apps

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Notes

Put any notes here

# Pivotal Tracker Link:

PT link here

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Backend/ServiceLayer/Services/KFC_SSO_APIService.cs
> +        public static readonly string APISecret = "5E5DDBD9B984E4C95BBFF621DF91ABC9A5318DAEC0A3B231B4C1BC8FE0851610";
Does API secret need to be updated? To ->
FDF9B8E2935D6F4C7336604164B92B82E36D1BD87FF96333194D41FDDA023449
Unless this is  the new secret generated when reregistering our application

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Backend/ServiceLayer/Services/KFC_SSO_APIService.cs
> +        public class DeleteUserFromSSO_DTO
make DTO seperate class and store it with other DTOs

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Backend/ServiceLayer/Services/TokenService.cs
Purpose of moving individual app secret to KFC_SSO_APIService?

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Backend/WebApi-PointMap/Controllers/UserController.cs
> +        [HttpDelete]
This route been tested to shown it works with CORS? I had issues with logout route using HttpDelete, did you encounter any?

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Backend/WebApi-PointMap/Controllers/UserController.cs
> +            var token = GetHeader(Request, "Token");
Use controllerhelper method for token retrieval

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Backend/WebApi-PointMap/Controllers/UserController.cs
> +                    var session = _sessionService.ValidateSession(_db, token);
ControllerHelper has methods to validate and update session
See how its done in PointController route: [Route("api/point/{guid}")]

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Backend/WebApi-PointMap/Controllers/UserController.cs
> +                    var _ssoAPI = new KFC_SSO_APIService();
Should not be calling a service from a controller

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Backend/WebApi-PointMap/Controllers/UserController.cs
> +                    return Content((HttpStatusCode)500, ex.Message);
Make sure you are using proper error handling class luke made to catch and processes errors

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Backend/WebApi-PointMap/Controllers/UserController.cs
> +        class UserRequestDTO
Not sure the purpose of a DTO that is only one variable

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Frontend/src/components/Navbar.vue
> +          { title: 'Account', link: '/account'},
Shouldn't label this account if it only deletes the account, would be nice though if it displayed information of the account. Otherwise rename this deleteAccount. Make sure there is a check verifying the user wants to carry through with this action

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Frontend/src/views/Account.vue
> +            .then(response => {
Also catch 401 responses and resend to login

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Frontend/src/views/Account.vue
> +export default {
A whole page for deleting account response seems a little overkill have you considered just making this a popup alert. User selects deleteAccount from menu -> popup asks are you sure you want to delete account, red button for Yes, green for No. -> Confirming will either send them to login on SSO if it works or display an alert showing if the user failed. && user selects no popup goes away.

2019-04-18 19:06 UTC, ChrisMeyer7088 commented on Frontend/src/views/Account.vue
> +export default {
If interested in making this a popup, look into modal components
This is a good link with a good tutorial
https://alligator.io/vuejs/vue-modal-component/

2019-04-18 21:35 UTC, alfredovargasjr commented on Backend/ServiceLayer/Services/KFC_SSO_APIService.cs
> +        public static readonly string APISecret = "5E5DDBD9B984E4C95BBFF621DF91ABC9A5318DAEC0A3B231B4C1BC8FE0851610";
This is the new secret since we had to reregister

2019-04-18 21:35 UTC, alfredovargasjr commented on Backend/ServiceLayer/Services/KFC_SSO_APIService.cs
> +        public class DeleteUserFromSSO_DTO
Got it

2019-04-18 21:35 UTC, alfredovargasjr commented on Backend/ServiceLayer/Services/TokenService.cs
I want to move everything that is specific for KFCSSO into its own service.

2019-04-18 21:35 UTC, alfredovargasjr commented on Backend/WebApi-PointMap/Controllers/UserController.cs
> +        [HttpDelete]
I modified the web.config to accept put/delete options

2019-04-18 21:35 UTC, alfredovargasjr commented on Frontend/src/components/Navbar.vue
> +          { title: 'Account', link: '/account'},
account page with prompt user to options, either delete from pointmap, or sso

2019-04-18 21:35 UTC, alfredovargasjr commented on Frontend/src/views/Account.vue
> +export default {
Account page will also display username,user id, etc. It is an account page that include a bit of info of the user and account options (delete from pointmap, delete from sso)

2019-04-20 14:23 UTC, ChrisMeyer7088 commented on Backend/ServiceLayer/Services/TokenService.cs
Not specific for KFCSSO since I use the shared secret for authorization with the logging server

2019-04-20 14:27 UTC, ChrisMeyer7088 commented on Backend/ServiceLayer/Services/TokenService.cs
Actually I like that better, since if we have to change secret, we don't need to relaunch logging

2019-04-20 14:45 UTC, ChrisMeyer7088 requested changes

2019-04-20 14:45 UTC, ChrisMeyer7088 commented on Backend/WebApi-PointMap/Controllers/UserController.cs
> +                    var _ssoAPI = new KFC_SSO_APIService();
Still need to resolve this

2019-04-20 14:45 UTC, ChrisMeyer7088 commented on Frontend/src/services/accountServices.js
> +let config = {
still need to look for an unauthorized response and trigger logout on receiving the response. Having the catch redirect statement is a ghetto way of doing it, instead we should trigger the logout function in authorizationServices, which deletes the token from the Server, clears local storage, and redirects you

2019-04-20 14:45 UTC, ChrisMeyer7088 commented on Frontend/src/services/accountServices.js
> +let config = {
The logout route still needs some work since it hasn't changed since when I did it in our call, but that's ryan's task

2019-04-21 17:07 UTC, ChrisMeyer7088 approved these changes

2019-04-23 01:47 UTC, merged