Point editor looks better
CECS-491A/core pull request #129
Opened 2019-05-09 03:28 UTC by Luke-Clements

# Description

UI updates.

## Type of change

UI

# How Has This Been Tested?

Manually on localhost

2019-05-09 05:07 UTC, alfredovargasjr approved these changes

2019-05-09 05:17 UTC, Luke-Clements commented
Don't merge it! There is one thing still not working properly.

2019-05-09 05:18 UTC, alfredovargasjr requested changes
Not ready

2019-05-13 03:47 UTC, alfredovargasjr approved these changes

2019-05-13 04:07 UTC, alfredovargasjr requested changes
Adding notifcations

2019-05-13 10:12 UTC, alfredovargasjr approved these changes

2019-05-13 19:58 UTC, alfredovargasjr requested changes

2019-05-13 19:58 UTC, alfredovargasjr commented on Frontend/src/views/PointEditor.vue
> +            <v-snackbar
Can you make this a color=success

2019-05-13 21:07 UTC, alfredovargasjr approved these changes

2019-05-13 21:07 UTC, merged